### ISSUE TITLE
Fehler im Frontend

### ISSUE THREAD

**Issue by CrawlingKing** [MetaModels/attribute_rating#6]
Hi,
bei mir produziert das [rating]-Attribut unter contao 3.2.7 leider diese Fehler : 

```php
Warning: file_exists() expects parameter 1 to be a valid path, string given in I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodelsattribute_rating\MetaModels\Attribute\Rating\Rating.php on line 285

#0 [internal function]: __error(2, 'file_exists() e...', 'I:\LebeLowCarb-...', 285, Array)
#1 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodelsattribute_rating\MetaModels\Attribute\Rating\Rating.php(285): file_exists('I:\LebeLowCarb-...')
#2 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodelsattribute_rating\MetaModels\Attribute\Rating\Rating.php(313): MetaModels\Attribute\Rating\Rating->ensureImage('?????????????7...', 'system/modules/...')
#3 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Attribute\Base.php(377): MetaModels\Attribute\Rating\Rating->prepareTemplate(Object(MetaModels\Render\Template), Array, Object(MetaModels\Render\Setting\Simple))
#4 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Item.php(87): MetaModels\Attribute\Base->parseValue(Array, 'xhtml', Object(MetaModels\Render\Setting\Simple))
#5 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Item.php(359): MetaModels\Item->internalParseAttribute(Object(MetaModels\Attribute\Rating\Rating), 'xhtml', Object(MetaModels\Render\Setting\Collection))
#6 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Items.php(246): MetaModels\Item->parseValue('xhtml', Object(MetaModels\Render\Setting\Collection))
#7 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Items.php(261): MetaModels\Items->parseValue('xhtml', Object(MetaModels\Render\Setting\Collection))
#8 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\ItemList.php(741): MetaModels\Items->parseAll('xhtml', Object(MetaModels\Render\Setting\Collection))
#9 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\FrontendIntegration\Module\ModelList.php(104): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Module\ModelList))
#10 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\Module.php(148): MetaModels\FrontendIntegration\Module\ModelList->compile()
#11 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\FrontendIntegration\Module\ModelList.php(59): Contao\Module->generate()
#12 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\elements\ContentModule.php(63): MetaModels\FrontendIntegration\Module\ModelList->generate()
#13 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Controller.php(456): Contao\ContentModule->generate()
#14 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\ModuleArticle.php(205): Contao\Controller->getContentElement(Object(Contao\ContentModel), 'main')
#15 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\Module.php(148): Contao\ModuleArticle->compile()
#16 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\ModuleArticle.php(59): Contao\Module->generate()
#17 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Controller.php(392): Contao\ModuleArticle->generate(false)
#18 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Controller.php(254): Contao\Controller->getArticle(Object(Contao\ArticleModel), false, false, 'main')
#19 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\pages\PageRegular.php(138): Contao\Controller->getFrontendModule('0', 'main')
#20 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(249): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(433): Index->run()
#22 {main}


Warning: file_exists() expects parameter 1 to be a valid path, string given in I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodelsattribute_rating\MetaModels\Attribute\Rating\Rating.php on line 285

#0 [internal function]: __error(2, 'file_exists() e...', 'I:\LebeLowCarb-...', 285, Array)
#1 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodelsattribute_rating\MetaModels\Attribute\Rating\Rating.php(285): file_exists('I:\LebeLowCarb-...')
#2 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodelsattribute_rating\MetaModels\Attribute\Rating\Rating.php(317): MetaModels\Attribute\Rating\Rating->ensureImage('?8B??}????????7...', 'system/modules/...')
#3 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Attribute\Base.php(377): MetaModels\Attribute\Rating\Rating->prepareTemplate(Object(MetaModels\Render\Template), Array, Object(MetaModels\Render\Setting\Simple))
#4 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Item.php(87): MetaModels\Attribute\Base->parseValue(Array, 'xhtml', Object(MetaModels\Render\Setting\Simple))
#5 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Item.php(359): MetaModels\Item->internalParseAttribute(Object(MetaModels\Attribute\Rating\Rating), 'xhtml', Object(MetaModels\Render\Setting\Collection))
#6 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Items.php(246): MetaModels\Item->parseValue('xhtml', Object(MetaModels\Render\Setting\Collection))
#7 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Items.php(261): MetaModels\Items->parseValue('xhtml', Object(MetaModels\Render\Setting\Collection))
#8 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\ItemList.php(741): MetaModels\Items->parseAll('xhtml', Object(MetaModels\Render\Setting\Collection))
#9 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\FrontendIntegration\Module\ModelList.php(104): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Module\ModelList))
#10 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\Module.php(148): MetaModels\FrontendIntegration\Module\ModelList->compile()
#11 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\FrontendIntegration\Module\ModelList.php(59): Contao\Module->generate()
#12 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\elements\ContentModule.php(63): MetaModels\FrontendIntegration\Module\ModelList->generate()
#13 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Controller.php(456): Contao\ContentModule->generate()
#14 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\ModuleArticle.php(205): Contao\Controller->getContentElement(Object(Contao\ContentModel), 'main')
#15 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\Module.php(148): Contao\ModuleArticle->compile()
#16 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\ModuleArticle.php(59): Contao\Module->generate()
#17 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Controller.php(392): Contao\ModuleArticle->generate(false)
#18 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Controller.php(254): Contao\Controller->getArticle(Object(Contao\ArticleModel), false, false, 'main')
#19 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\pages\PageRegular.php(138): Contao\Controller->getFrontendModule('0', 'main')
#20 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(249): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(433): Index->run()
#22 {main}


Warning: file_exists() expects parameter 1 to be a valid path, string given in I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodelsattribute_rating\MetaModels\Attribute\Rating\Rating.php on line 285

#0 [internal function]: __error(2, 'file_exists() e...', 'I:\LebeLowCarb-...', 285, Array)
#1 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodelsattribute_rating\MetaModels\Attribute\Rating\Rating.php(285): file_exists('I:\LebeLowCarb-...')
#2 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodelsattribute_rating\MetaModels\Attribute\Rating\Rating.php(321): MetaModels\Attribute\Rating\Rating->ensureImage('?????}????????7...', 'system/modules/...')
#3 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Attribute\Base.php(377): MetaModels\Attribute\Rating\Rating->prepareTemplate(Object(MetaModels\Render\Template), Array, Object(MetaModels\Render\Setting\Simple))
#4 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Item.php(87): MetaModels\Attribute\Base->parseValue(Array, 'xhtml', Object(MetaModels\Render\Setting\Simple))
#5 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Item.php(359): MetaModels\Item->internalParseAttribute(Object(MetaModels\Attribute\Rating\Rating), 'xhtml', Object(MetaModels\Render\Setting\Collection))
#6 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Items.php(246): MetaModels\Item->parseValue('xhtml', Object(MetaModels\Render\Setting\Collection))
#7 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\Items.php(261): MetaModels\Items->parseValue('xhtml', Object(MetaModels\Render\Setting\Collection))
#8 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\ItemList.php(741): MetaModels\Items->parseAll('xhtml', Object(MetaModels\Render\Setting\Collection))
#9 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\FrontendIntegration\Module\ModelList.php(104): MetaModels\ItemList->render('', Object(MetaModels\FrontendIntegration\Module\ModelList))
#10 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\Module.php(148): MetaModels\FrontendIntegration\Module\ModelList->compile()
#11 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\metamodels\MetaModels\FrontendIntegration\Module\ModelList.php(59): Contao\Module->generate()
#12 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\elements\ContentModule.php(63): MetaModels\FrontendIntegration\Module\ModelList->generate()
#13 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Controller.php(456): Contao\ContentModule->generate()
#14 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\ModuleArticle.php(205): Contao\Controller->getContentElement(Object(Contao\ContentModel), 'main')
#15 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\Module.php(148): Contao\ModuleArticle->compile()
#16 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\modules\ModuleArticle.php(59): Contao\Module->generate()
#17 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Controller.php(392): Contao\ModuleArticle->generate(false)
#18 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Controller.php(254): Contao\Controller->getArticle(Object(Contao\ArticleModel), false, false, 'main')
#19 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\pages\PageRegular.php(138): Contao\Controller->getFrontendModule('0', 'main')
#20 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(249): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#21 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(433): Index->run()
#22 {main}


Warning: Cannot modify header information - headers already sent by (output started at I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\helper\functions.php:70) in I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Template.php on line 298

#0 [internal function]: __error(2, 'Cannot modify h...', 'I:\LebeLowCarb-...', 298, Array)
#1 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Template.php(298): header('Vary: User-Agen...', false)
#2 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\classes\FrontendTemplate.php(210): Contao\Template->output()
#3 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\pages\PageRegular.php(183): Contao\FrontendTemplate->output(true)
#4 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(249): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#5 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(433): Index->run()
#6 {main}


Warning: Cannot modify header information - headers already sent by (output started at I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\helper\functions.php:70) in I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Template.php on line 299

#0 [internal function]: __error(2, 'Cannot modify h...', 'I:\LebeLowCarb-...', 299, Array)
#1 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\library\Contao\Template.php(299): header('Content-Type: t...')
#2 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\classes\FrontendTemplate.php(210): Contao\Template->output()
#3 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\system\modules\core\pages\PageRegular.php(183): Contao\FrontendTemplate->output(true)
#4 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(249): Contao\PageRegular->generate(Object(Contao\PageModel), true)
#5 I:\LebeLowCarb-Lokal\XAMPP\htdocs\neu\index.php(433): Index->run()
#6 {main}
```

Es wäre super, wenn das Attribut klappen würde ;)

Viele Grüße und vielen Dank Michael

**Comment by MiniModel** [comment]
This issue has been labeled with "testing" but got no feedback.

We are reliant on feedback to prove a ticket fixed as we can not tell if the ticket has been
resolved if we receive no feedback.
I will close this ticket now, as I assume it has been resolved.
If the ticket should still be valid, please feel free to reopen it.

@CrawlingKing could you please have a final look at this and tell if your issue has been resolved?
